# Generated by Django 2.2.1 on 2020-02-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200213_0929'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelciudad',
            table='Ciudad',
        ),
    ]
